version: '2'
services:
  postgres:
    image: "postgres"
    container_name: postgres
    env_file:
      - database.env
  user-api:
    image: user-api
    container_name: user-api
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
  batch-user-job:
    image: batch-user-job
    container_name: batch-user-job
    links:
      - user-api
      - postgres
    depends_on:
      - postgres