CREATE TABLE AUTH_USER_ROLE(
    USER_ID       UUID NOT NULL,
    ROLE_ID       UUID NOT NULL
);

ALTER TABLE AUTH_USER_ROLE ADD CONSTRAINT UP_FK_P_ID FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID);
ALTER TABLE AUTH_USER_ROLE ADD CONSTRAINT UNQ_USR_ID_PRL_ID UNIQUE (USER_ID, ROLE_ID);